Skipping tests if a provider does not support a primitive.
Exceptions should give some indication what went wrong with a test:
AssumptionViolatedException: thrown by TestUtil.skipTest() is thrown when
  the test could not be run (e.g., because the primitive is missing)
AssertionError: thrown if the test failed because the provider returned
  unexpected results.
Other exceptions: the test failed in an unexpected way. This can be either
  an incorrect test setup, a bug in the provider or an unusual implementation
  of an ambiguous interface. The goal is to distinguish provider bugs
  from test bugs. Hence the goal is to reduce such undefined exceptions as
  much as possible.
NOKEYCHECK=True
PiperOrigin-RevId: 497953671