Add a better error message to the DhTest.
A typical error message with the new JDK looks like this:

java.lang.AssertionError: X expected to have bit length 1504, but has value 92958950218418996462987643843877938499735925222249647906188789799246291415800, which has bit length 256

NOKEYCHECK=True
PiperOrigin-RevId: 548591594